# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: docker-compose environment
        run: |
          git clone https://github.com/sagecontinuum/sage-storage-api.git
          pushd sage-storage-api
          docker-compose up --build -d
          popd
      - name: install library
        run: pip install .
      - name: install other sage-cli dependencies
        run: pip install click
      - name: run CLI tests
        run: |
          git clone https://github.com/sagecontinuum/sage-cli.git
          cd sage-cli
          until curl -s http://localhost:8080/api/v1/ ; do echo "no connection..." ; sleep 1 ; done
          export SAGE_USER_TOKEN=user:testuser
          export SAGE_HOST=http://localhost:8080
          ./tests.sh
